# COPRA fan settings clone - generated by 'dumpsettings'
# Source fan: 19200 8E1, address 11
# Reload onto another fan with:  fan_tool -p <port> /home/msowa/Github/fan_tool/fan_settings_clone.fan
# writeraw uses raw register values, so they reload exactly.
# Note: comm-setting changes (baud/parity/address) only take
#       effect after a power cycle.

writeraw 35948 9   # direction = 9
writeraw 34409 5   # demand_source = 5
writeraw 34412 1   # modbus_priority = 1
writeraw 34418 2500   # default_demand = 25 %
writeraw 33395 0   # din1_function = 0
writeraw 33396 0   # din2_function = 0
writeraw 33397 0   # din3_function = 0
writeraw 33385 65535   # din_enable = 65535
writeraw 33386 8   # din_polarity = 8
writeraw 33897 192   # modbus_baud = 19200 baud
writeraw 33902 11   # modbus_address = 11
writeraw 33900 2   # modbus_parity = 2
writeraw 33899 1   # modbus_stop_bits = 1
writeraw 33905 20   # hb_timeout = 20 s
writeraw 33906 0   # loss_demand = 0 %

save   # persist all of the above to flash
